# Generated by Django 5.1.6 on 2025-09-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_signalevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoringsession',
            name='timeframe',
        ),
        migrations.AddField(
            model_name='monitoredstock',
            name='timeframe',
            field=models.CharField(default='5 Minutes', max_length=50),
            preserve_default=False,
        ),
    ]
