# Generated by Django 5.1.6 on 2025-09-26 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_monitoredstock_timeframe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoredstock',
            name='timeframe',
        ),
    ]
