# Generated by Django 5.1.6 on 2025-09-26 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_monitoredstock_timeframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredstock',
            name='timeframe',
            field=models.CharField(default='1h', max_length=50),
            preserve_default=False,
        ),
    ]
